import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
    justifyContent: "space-between",
    alignItems: "center",
  },
  contentContainer: {
    width: '100%',
    alignItems: "center",
  },
  contentText: {
    alignItems: "flex-start",
    alignSelf: "stretch",
    paddingHorizontal: 30,
    marginTop: 10,
  },
  challengeTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: "white",
    marginBottom: 4,
    fontFamily: "inter",
  },
  challengeDescription: {
    fontSize: 14,
    fontWeight: "700",
    color: "#C8C8C8",
    fontFamily: "inter",
  },
  recepientDataRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "stretch",
    paddingHorizontal: 30,
    paddingTop: 35,
  },
  timeTable: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E1E1E",
    borderRadius: 15,
    marginTop: 20,
    paddingVertical: 14,
    alignSelf: "stretch",
    marginHorizontal: 20,
    justifyContent: "center",
  },
  timeLeft: {
    fontSize: 24,
    fontWeight: "700",
    color: "white",
    marginBottom: 4,
    fontFamily: "inter",
    marginLeft: 5,
  },
  ExerciseContainer: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    alignSelf: "stretch",
    paddingHorizontal: 20,
    marginTop: 30,
  },
  backRoundIconExercise: {
    backgroundColor: "#1E1E1E",
    borderRadius: 15,
    width: 70,
    height: 70,
    marginRight: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  ExerciseRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    alignItems: "center",
    marginBottom: 10,
    justifyContent: "space-between",
  },
  procent: {
    color: "#C8C8C8",
    fontSize: 14,
    fontWeight: 700,
  },
  ExerciseTitle: {
    color: "white",
    fontSize: 24,
    fontFamily: "inter",
    fontWeight: 700,
  },
  buttonWrapper: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: 40, 
  },
  buttonGradient: {
    backgroundColor: "#9A5CEE",
    height: 50,
    width: 300,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    borderRadius: 25,
    position: "relative",
  },
  buttonGradientText: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 20,
    color: "#C8C8C8",
    fontWeight: "bold",
    fontFamily: "inter",
  },
  buttonContainer: {
    borderRadius: 25,
    overflow: "hidden",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
});